//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Home_Work.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HomeWorkDBEntities : DbContext
    {
        public HomeWorkDBEntities()
            : base("name=HomeWorkDBEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Contact_Message> Contact_Message { get; set; }
        public virtual DbSet<Contact_Messanger> Contact_Messanger { get; set; }
        public virtual DbSet<Job_HomeBase> Job_HomeBase { get; set; }
        public virtual DbSet<Job_Post> Job_Post { get; set; }
        public virtual DbSet<Job_SkillType> Job_SkillType { get; set; }
        public virtual DbSet<Job_WorkType> Job_WorkType { get; set; }
        public virtual DbSet<Portfolio_Image> Portfolio_Image { get; set; }
        public virtual DbSet<Profile_Education> Profile_Education { get; set; }
        public virtual DbSet<Profile_Portfolio> Profile_Portfolio { get; set; }
        public virtual DbSet<Profile_Training> Profile_Training { get; set; }
        public virtual DbSet<Profile_User> Profile_User { get; set; }
        public virtual DbSet<Profile_Work> Profile_Work { get; set; }
        public virtual DbSet<Profile_WorkStatus> Profile_WorkStatus { get; set; }
    }
}
